### ISSUE TITLE
Click Button

### ISSUE THREAD

**Issue by Meike-Ka** [Meike-Ka/capstone-project#1]
## Value Proposition

**As a** student
**I want to** I press the button
**so that** that the categories are displayed 
​

## Description

![Unbenannt-2023-07-27-0806](https://github.com/Meike-Ka/capstone-project/assets/128140277/e4bc89ef-1092-4f75-aac6-31a54d33315c)

​

## Acceptance Criteria

- [ ] My four categories are displayed
- [ ] e.g all inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] create a new branch
- [ ] create click button 
- [ ] ...
      ​
