### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by Meike-Ka** [Meike-Ka/capstone-project#3]
## Value Proposition

**As a** student  
**I want to** I press the button 
**so that** to create a feature where a button can be pressed to display four categories.

## Description

![Unbenannt-2023-07-27-0806](https://github.com/Meike-Ka/capstone-project/assets/128140277/3382f99e-ef26-44e1-a58b-304b20eaea44)

​

## Acceptance Criteria

- [ ]  When the user presses the button, all four categories are immediately displayed on the screen.
- [ ]  The categories should be neatly organized and visually distinguishable from each other for easy identification
      ​

## Tasks

- [ ] Create a new branch
- [ ]  Implement the button's click functionality.
- [ ]  When I press the button, all four categories are displayed.
      ​

## Complexity

S

**Comment by Kheirah** [comment]
The value proposition is somewhat confusingly put 😃 

Let's rephrase it a bit into:
As a student
I want to see a list of categories
so that I can select which category I want to associate my note with.
